// Regenerates data/ from the IANA time zone database. Run it when tzdata
// releases; the generated files are committed so the package needs no network
// and no dependencies at install or run time.
//
// Three files, three jobs:
//   zone-country  zone.tab, one country per zone. The lookup table.
//   zone-alias    the compatibility links, because a browser may report either
//                 spelling and ICU does not normalise them.
//
// zone.tab is cross-checked against this runtime's ICU region data, because a
// tzdb Link means "same clock", not "same place". America/Coral_Harbour is
// linked to America/Panama over a shared offset, but it is in Canada; likewise
// Africa/Asmera (Eritrea, linked to Nairobi in Kenya) and Pacific/Ponape and
// Pacific/Truk (Micronesia, linked to Guadalcanal and Port Moresby). Following
// those links for geography answers with the wrong country, so any zone ICU
// knows that zone.tab omits is taken from ICU instead.
//
// zone1970.tab is deliberately NOT used. It groups countries whose clocks have
// agreed since 1970, so Europe/Berlin covers DE, DK, NO, SE and SJ. That looks
// like detection ambiguity but is not: every co-tenant country has its own
// zone.tab name (Europe/Copenhagen, Europe/Oslo, Europe/Stockholm), so a
// machine in those countries reports that name instead. Checked against tzdata
// 2026c: of the 34 multi-country rows, zero have a co-tenant lacking its own
// zone. Treating them as ambiguous would have flagged most of Europe and all
// of Japan as low confidence for nothing.
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const BASE = 'https://data.iana.org/time-zones/data';
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'data');

const get = async (file) => {
  const res = await fetch(`${BASE}/${file}`);
  if (!res.ok) throw new Error(`${file}: HTTP ${res.status}`);
  return res.text();
};

const rows = (text) =>
  text.split('\n').filter((l) => l && !l.startsWith('#')).map((l) => l.split('\t'));

const banner = (file) =>
  `// Generated by scripts/build-data.js from IANA ${file}. Do not edit by hand.\n`;

const [version, zoneTab, backward] = await Promise.all(
  ['version', 'zone.tab', 'backward'].map(get)
);
const tzdata = version.trim();

// zone.tab is deliberately the source rather than zone1970.tab: every row has
// exactly one country, and it keeps the microstate zone names that zone1970
// folds away (Europe/Vaduz, Europe/Vatican, Arctic/Longyearbyen, ...). Those
// names are what a browser in those countries actually reports.
const byCountry = new Map();
for (const [cc, , zone] of rows(zoneTab)) {
  if (!/^[A-Z]{2}$/.test(cc) || !zone) continue;
  if (!byCountry.has(cc)) byCountry.set(cc, []);
  byCountry.get(cc).push(zone);
}
// ICU lists zones zone.tab leaves out, and it places them geographically rather
// than by clock. Only the reverse direction exists in the platform (region ->
// zones), so every known region is asked and the answers inverted.
//
// This is a hard requirement, not a nicety. getTimeZones landed after Node 22,
// and running this script without it would quietly emit a table missing the
// corrections, putting Eritrea back in Kenya. Failing here is the only way that
// stays visible.
if (typeof Intl.Locale.prototype.getTimeZones !== 'function') {
  throw new Error(
    `Intl.Locale.prototype.getTimeZones is unavailable on ${process.version}. ` +
      'Regenerate the data on Node 24 or newer: without it, zones that zone.tab ' +
      'omits would be resolved through tzdb links, which answer with the country ' +
      'of whatever zone shares their clock rather than where they are.'
  );
}
const inZoneTab = new Set([...byCountry.values()].flat());
const fromIcu = new Map();
for (const cc of byCountry.keys()) {
  let zones;
  try {
    zones = new Intl.Locale(`und-${cc}`).getTimeZones();
  } catch {
    continue;
  }
  for (const zone of zones ?? []) {
    if (!inZoneTab.has(zone) && !fromIcu.has(zone)) fromIcu.set(zone, cc);
  }
}
for (const [zone, cc] of fromIcu) byCountry.get(cc).push(zone);
if (fromIcu.size) {
  console.log(`ICU added ${fromIcu.size} zones absent from zone.tab: ${[...fromIcu].map(([z, c]) => `${z}=${c}`).join(', ')}`);
}

for (const zones of byCountry.values()) zones.sort();

const zoneCount = [...byCountry.values()].reduce((n, z) => n + z.length, 0);
const packedZones = [...byCountry]
  .sort(([a], [b]) => (a < b ? -1 : 1))
  .map(([cc, zones]) => `${cc}:${zones.join(',')}`)
  .join(';');

// Grouped by target, since many aliases share one. Trailing "#=" comments and
// the irregular tab runs in the source both have to go.
const byTarget = new Map();
for (const line of backward.split('\n')) {
  if (!line.startsWith('Link')) continue;
  const [, target, alias] = line.replace(/#.*$/, '').trim().split(/\s+/);
  if (!target || !alias) continue;
  if (!byTarget.has(target)) byTarget.set(target, []);
  byTarget.get(target).push(alias);
}
const aliasCount = [...byTarget.values()].reduce((n, a) => n + a.length, 0);
const packedAliases = [...byTarget]
  .sort(([a], [b]) => (a < b ? -1 : 1))
  .map(([target, aliases]) => `${target}:${aliases.join(',')}`)
  .join(';');


writeFileSync(
  join(OUT, 'zone-country.js'),
  `${banner('zone.tab')}// ${zoneCount} zones across ${byCountry.size} countries, tzdata ${tzdata}.\n` +
    `export const PACKED_ZONE_COUNTRY = '${packedZones}';\n`
);
writeFileSync(
  join(OUT, 'zone-alias.js'),
  `${banner('backward')}// ${aliasCount} compatibility links, tzdata ${tzdata}.\n` +
    `export const PACKED_ZONE_ALIAS = '${packedAliases}';\n`
);
writeFileSync(
  join(OUT, 'version.js'),
  `${banner('version')}export const TZDATA_VERSION = '${tzdata}';\n`
);

console.log(`tzdata ${tzdata}: ${zoneCount} zones, ${byCountry.size} countries, ${aliasCount} aliases`);
